### PR TITLE
Port to godot 4

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Working on making this work with Godot 4.0.

Getting real close to this working with the new GD Extensions, with loads of workarounds :)

You need to build Godot with this PR included: https://github.com/godotengine/godot/pull/52532 and https://github.com/godotengine/godot/pull/52864

Godot-cpp should point to my branch with array fixes but make sure you update the `extensions_api.json` and `gdnative_interface.h` in there

Issues so far:
- controllers are broken as the old GDNative API calls are gone, working on using XRPositionalTrackers directly
- lighting is broken in the mobile renderer

### CODE REVIEW

**Comment by beniwtv** [comment]
Nice! I shall have a go at it this week :)

**Comment by BastiaanOlij** [comment]
> 
> 
> Nice! I shall have a go at it this week :)

I just got all the basics to work, albeit with many shortcuts. Getting it all compiled takes some creativity as many things are in flux, especially the Godot 4 GDNative work vnen is doing. 

I'm currently without solid internet so I'm hoping in and out of Discord but that should be resolved by Thursday. Hit me up when you want to try and I'll talk you through the process

**Comment by beniwtv** [comment]
Sure, will do

**Comment by BastiaanOlij** [comment]
I'm still having a weird issue with stereo rendering, I think the eye position is slightly off, might have something to do with the way we add some of the offset to the projection matrix in Godot 4.
Also the output currently is too dark so OpenVR is not applying the correct color balancing.

That said, I fixed tracking issues and have finger tracking working again as well :)

**Comment by beniwtv** [comment]
So with the fix in github.com/vnen/godot-cpp/pull/7 I was able to compile it. I also had to change "X11" to "Linux" manually in the gdnlib file as the editor still uses the old X11 as platform :)

Unforunately, upon launching the demo, I get a crash:

```
Application in scene (normal) mode.
Main OpenVR interface has been initialized
Main render models interface has been initialized.
Exec path: /home/beniwtv/build/godot/bin
Project path: /home/beniwtv/build/godot_openvr_bastiaan/demo/
Loaded action json from: /home/beniwtv/build/godot_openvr_bastiaan/demo/actions/actions.json
Bound action /actions/godot/in/trigger to 1153008786932236590
Bound action /actions/godot/in/analog_trigger to 1153008786932236591
Bound action /actions/godot/in/grip to 1153008786932236592
Bound action /actions/godot/in/analog_grip to 1153008786932236593
Bound action /actions/godot/in/analog to 1153008786932236594
Bound action /actions/godot/in/analog_click to 1153008786932236595
Bound action /actions/godot/in/button_ax to 1153008786932236596
Bound action /actions/godot/in/button_by to 1153008786932236597
Bound action /actions/godot/out/haptic to 1153008786932236599
Failed to obtain action set handle for /actions/godot
Bound action /actions/godot/in/left_hand to 1153008786932236606
Bound action /actions/godot/in/right_hand to 1153008786932236606
Found HMD 0 (generic_hmd)
Found base station 1 (lh_basestation_valve_gen2)
Found base station 2 (lh_basestation_valve_gen2)
Found controller 3 ({indexcontroller}valve_controller_knu_1_0_right)
Controller {indexcontroller}valve_controller_knu_1_0_right_3 became active
Loading: {indexcontroller}valve_controller_knu_1_0_right
Couldn't retrieve skeletal action data, err: 3
Couldn't retrieve skeletal action data, err: 3
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7fd92a25bda0] (??:0)
-- END OF BACKTRACE --
```

**Comment by BastiaanOlij** [comment]
Crappy the backtrace is incomplete. Doesn't really tell us what is going on :(

Yeah I think there have been a few fixes/improvements in GDNative that were done in the 3.x branch after all the Vulkan work was merged into master that never made it into the master branch.

**Comment by BastiaanOlij** [comment]
A little progress update in the form of a video:

https://youtu.be/Om6a1KF297I

**Comment by BastiaanOlij** [comment]
Hey @beniwtv , got the Linux build going thanks to a tip from Akien, just needed a newer version of Python so switched it to using ubuntu 20
You might want to give it a twirl :)

**Comment by beniwtv** [comment]
Nice! I guess we can switch to 20.04-level now anyway, should be "old" enough for most distros. Will give it a try later :)

**Comment by BastiaanOlij** [comment]
Probably won't work, something new broke in GDNative:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] godot::___godot_icall_bool_String (D:\Development\xr_plugins\godot_openvr.4.0\godot-cpp\include\gen\__icalls.hpp:1596)
[1] godot::Directory::file_exists (D:\Development\xr_plugins\godot_openvr.4.0\godot-cpp\src\gen\Directory.cpp:68)
[2] openvr_data::initialise (D:\Development\xr_plugins\godot_openvr.4.0\src\open_vr\openvr_data.cpp:198)
[3] godot_arvr_initialize (D:\Development\xr_plugins\godot_openvr.4.0\src\ARVRInterface.cpp:87)
[4] XRInterfaceGDNative::initialize (D:\Development\godot4-git\modules\gdnative\xr\xr_interface_gdnative.cpp:146)
[5] call_with_ptr_args_ret_helper<XRInterface,bool> (D:\Development\godot4-git\core\variant\binder_common.h:249)
```

String handling is SO broken

**Comment by BastiaanOlij** [comment]
Ok, I'm rebasing my https://github.com/godotengine/godot/pull/49301 to Godot master from a couple of days ago when GDNative isn't broken and then updating this accordingly.

**Comment by BastiaanOlij** [comment]
Still working on this so it doesn't work yet but busy rewriting this to using the new GD Extensions.

**Comment by BastiaanOlij** [comment]
Most objects have now been rewritten to the new GD extension format, working through the last series of compiler issues...

**Comment by gyroninja** [comment]
I tried fixing the compilation errors myself along with fixing some stuff with the demo project https://github.com/gyroninja/godot_openvr/tree/8729d645ea75e3f874855a26cfdd702aa0053720 but it seems like there are a few things missing before it will actually work.

In `openvr_library_init` `godot::GDExtensionBinding::init` fails https://github.com/godotengine/godot-cpp/blob/d9258ee0e87dfbde1cece7adc1261c7f6b8c9c3c/src/godot.cpp#L68

From what I can tell XRInterfaceOpenVR needs to register itself with XRServer, but I don't think it does this yet.

**Comment by BastiaanOlij** [comment]
@gyroninja owh yes, there is a lot missing at the moment. the last time this worked it was still using GDNative, the new GD Extension system still has a lot of rough edges. I've been trying to fix things and find workaround all week. Getting pretty close to it sort of running with a lot of bandaid :)

**Comment by BastiaanOlij** [comment]
Need to find a nice way to implement this but as a workaround, this change is needed in Godot:
```
RID XRInterfaceExtension::get_render_target_texture(RID p_render_target) {
	// RendererStorage *storage = RSG::storage;
	// ERR_FAIL_NULL_V_MSG(storage, RID(), "Renderer storage not setup");

	// This needs to be implemented in a better way I guess...
	RendererStorageRD * rd_storage = RendererStorageRD::base_singleton;
	ERR_FAIL_NULL_V_MSG(rd_storage, RID(), "Renderer storage not setup");

	return rd_storage->render_target_get_rd_texture(p_render_target);
}
```

**Comment by BastiaanOlij** [comment]
It runs for me at the moment but it horribly crashes on exit. Part of that is due to constructors not being run (bug in GD extensions) but also because cleanup has moved and things are getting destroyed in the wrong order.. 

Still seeing output in my headset for the first time using the new GD Extension system is a definite win for tonight!

**Comment by BastiaanOlij** [comment]
Ok everyone, I rebased everything on the official release of `GDExtensions` and its working like a charm. You do need some things that were merged into Godot itself today so you should build from master.

Also with it being linked to the official release of `GDExtensions` the submodule should now be pointing to a usable commit hash (this turned out to be a problem with it pointing to a hash on my personal repo, git didn't like that).

Next step is getting controllers to work again

**Pull request merged**
