### PR TITLE
Update to godot-cpp for Godot 3.3, OpenVR 1.16.8 and add new functions

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Update upstream resources. Needs testing.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
What the...... they removed 64bit binaries from OSX? That sucks.

**Comment by BastiaanOlij** [comment]
Seems the OSX binaries are now universal binaries containing both 32bit and 64bit implementations just stored in `osx64`. Lets see if we can get it compiled. Someone else will have to test if it still works though.

**Comment by BastiaanOlij** [comment]
Removed the OSX build, does not seem supported anymore

**Comment by beniwtv** [comment]
Will do and let you know

**Review by beniwtv — APPROVED** [review]
Works all fine on Linux here :)

**Pull request merged**
