### PR TITLE
RGBA16F HDR to RGBA8 conversion to make OpenVR happy

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This is still experimental. I'm waiting on feedback on the OpenVR issue tracker to see if there is a better option.

Because OpenVR can't seem to use our RGBA16F buffer directly this PR introduces an extra step where the buffer is converted from RGBA16F to RGBA8 before being handed to OpenVR. There is an obvious overhead in this but how noticable, I'm not sure. I would rather prevent this from happening. There is a marked improvement in render quality though.

Testing this on my laptop with a GeForce 1060 and Fracteeds demo, the framerate drops to an uncomfortable 40fps but that is a complex scene with GI Probe. It'll be interesting to see what it does with a lightmap. Also I do not know whether this is due to rendering to an HDR buffer, the extra processing done on the HDR buffer, or the copy that was introduced.

### CODE REVIEW

**Comment by fire** [comment]
What was the original framerate / frame time?

**Comment by BastiaanOlij** [comment]
Don't know, I don't have accurate timing info. Should really hack in some code to properly time this:)

**Comment by fire** [comment]
found the bug

```diff
-export (NativeScript) var openvr_render_model_native
 
func _ready():
        # instance our render model object
-        ovr_render_model = openvr_render_model_native.new()
        ovr_render_model = preload("res://addons/openvr/openvr_render_model.gdns").new()
```

Export variables interact very badly with native script.

That was annoying.

**Comment by fire** [comment]
Ignore the previous post.

This method of hdr to ldr only works with single threaded safe mode.

Multithreaded fails.

**Comment by BastiaanOlij** [comment]
I rebased this and started using the slightly newer code I wrote for the oculus driver to blit the HDR buffer. 

Still have no idea how to solve the multi threading issue though... Could use some help from someone who understands the issues involved better. I think we're having the same issue with multithreading on oculus and it may be related to the opengl context not being correct.

**Comment by BastiaanOlij** [comment]
If accepted, this change in Godot itself will resolve this internally:
https://github.com/godotengine/godot/pull/19724

**Comment by BastiaanOlij** [comment]
Rebased, still crashes on compiling the shaders in multi-tasking mode.

**Comment by BastiaanOlij** [comment]
It's a little dirty but this no longer crashes in when multi-tasking.

Only thing left to do is add a nice way to make the HDR conversion logic optional as it should be off if HDR is not used (like with GLES2).

**Comment by BastiaanOlij** [comment]
I'm leaving this in place for now but this will soon be closed and not merged.

We've been in contact with Valve and we're finally getting an upstream fix!

**Comment by BastiaanOlij** [comment]
Closing this request. With the release of OpenVR 1.6.10 the HDR issue should be resolved upstream

**Comment by fire** [comment]
Thanks @BastiaanOlij and the OpenVR team!

**Pull request closed without merging**
