### PR TITLE
OpenVR actions.json file is loaded from one of 3 fixed locations

### LINKED ISSUE #95: Exported games are unable to find actions.json
Right now we have an issue in Godot (https://github.com/godotengine/godot/issues/36781) that prevents exported games with OpenVR from working, as SteamVR is unable to find **actions.json**.

The reason is that currently the function we use in the plugin uses **ProjectSettings.globalize_path()** to point SteamVR to the actions file. But this function returns a relative path in exported games, which SteamVR is unable to handle.

As a temporary workaround, one can set the path manually in the **OpenVRConfig** object to something like:

`OpenVRConfig.set_action_json_path(OS.get_executable_path() + "addons/godot_openvr/actions/actions.json")`

**Note:** Change path as needed, this is just for the default location of the JSON file inside the addon (which we recommend copying to another directory and adapting it as per https://github.com/GodotVR/godot-openvr-asset/wiki/OpenVR-actions).

**Note 2:** This will probably not work on systems like Android / iOS, adapt as needed (but I think there is no OpenVR there in any case (?)).

### PR DESCRIPTION
**Pull request by BastiaanOlij**
The plugin will now look for the actions.json file in 3 fixed locations:
1) in an actions folder along side the executable
2) in an actions folder within the projects folder
3) in an actions folder within our plugin

When exporting the project the actions folder will be exported as well so in runtime it always exists alongside the exe

Fixes #95

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Ok guys, I think I got this working right now.

I'll need to update the documentation accordingly but it will now copy the actions files on export into a folder put alongside the executable.

Only tested this one Windows so would be cool if people test this on other platforms too.

**Comment by beniwtv** [comment]
Will test it this evening and let you know

**Comment by beniwtv** [comment]
Looks good, everything seemed to work for me.

**Comment by BastiaanOlij** [comment]
> 
> 
> Looks good, everything seemed to work for me.

Then I think it's time to merge this in :)

**Pull request merged**
